// Headless logic check with a small DOM/WebGL stub; no visual browser assertion.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/embed.html','utf8'),els=new Map();
function element(id){if(!els.has(id))els.set(id,{id,hidden:false,textContent:'',value:'',style:{},classList:{toggle(){},remove(){}},appendChild(){},append(){},replaceChildren(){},addEventListener(){},click(){},clientWidth:520,clientHeight:1040,getBoundingClientRect:()=>({left:0,top:0,width:520,height:1040})});return els.get(id);}
class Obj{constructor(geometry){this.geometry=geometry;this.position={x:0,y:0,z:0,set(x,y,z){Object.assign(this,{x,y,z});}};this.scale={setScalar(){},y:1};this.rotation={z:0};this.material={color:{set(){}},opacity:1};}add(){}updateProjectionMatrix(){}setPixelRatio(){}setSize(){}render(){}setFromPoints(){return this;}}
class Vec{constructor(x=0,y=0,z=0){Object.assign(this,{x,y,z});}unproject(){this.x*=68;this.y*=126;return this;}set(x,y){Object.assign(this,{x,y});}lerp(){}}
const THREE=new Proxy({MathUtils:{clamp:(n,a,b)=>Math.max(a,Math.min(b,n))},Vector3:Vec,Vector2:Vec,WebGLRenderer:class extends Obj{constructor(){super();this.domElement=element('canvas');}},BufferGeometry:class extends Obj{constructor(){super();this.attributes={position:{setXYZ(){},needsUpdate:false}};}}},{get:(o,k)=>o[k]||Obj});
let callback;const messages=[];const ctx={THREE,console,performance,Date,Math,crypto:{},devicePixelRatio:1,document:{getElementById:element,createElement:element},sessionStorage:{getItem:()=>null,setItem(){}},location:{pathname:'/',protocol:'https:'},ResizeObserver:class{constructor(fn){this.fn=fn;}observe(){this.fn();}},requestAnimationFrame:fn=>callback=fn,setTimeout,clearTimeout,setInterval,clearInterval,WebSocket:{OPEN:1}};
ctx.globalThis=ctx;vm.createContext(ctx);const script=html.split('<script type="module">')[1].split('</script>')[0].replace(/^import .*;\n/m,'');vm.runInContext(script+`\nglobalThis.api={stateUI,predict,pointer,animate,bind:()=>ws={readyState:1,send:raw=>messages.push(JSON.parse(raw))}};`,Object.assign(ctx,{messages}));const api=ctx.api;api.bind();
const s={id:'TEST',status:'playing',players:['A','B'],ready:[true,true],score:[0,0],server:0,round:1,serverTime:Date.now(),ball:{x:0,y:60,z:30,vx:0,vy:-140,vz:0,phase:'flight',last:1,shot:2,bounces:1,cooldown:0,spin:0},paddles:[{x:50,y:-90},{x:0,y:90}]};
api.stateUI(s);api.animate(performance.now());api.pointer({clientX:260,clientY:850});api.animate(performance.now()+20);assert(messages.some(m=>m.type==='move'));assert.equal(element('nr-center').hidden,true);assert(Number.isFinite(api.predict(performance.now()).ball.z));s.round=2;s.ball.phase='serve';s.ball.y=-88;s.ball.z=10;s.ball.vx=s.ball.vy=s.ball.vz=0;api.stateUI(s);api.animate(performance.now()+30);s.status='paused';api.stateUI(s);api.animate(performance.now()+40);assert.equal(element('nr-center').hidden,false);
console.log('PASS: client initializes without secure-context randomUUID, state UI, pointer input, prediction, round reset, pause render');
