const {spawn}=require('node:child_process'),assert=require('node:assert/strict');const WebSocket=require('ws');
const port=8097;let proc;const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function client(){const ws=new WebSocket(`ws://127.0.0.1:${port}`);const c={ws,events:[],side:0,auto:false,lastServe:-1,lastShot:0};ws.on('message',raw=>{const m=JSON.parse(raw);c.events.push(m);if(m.type==='joined')c.side=m.side;if(m.type==='state'){c.latest=m;c.lastShot=Math.max(c.lastShot,m.ball.shot||0);if(c.auto&&m.status==='playing'){
 const b=m.ball,sg=c.side===0?1:-1;
 if(b.phase==='serve'&&m.server===c.side&&c.lastServe!==m.round){c.lastServe=m.round;ws.send(JSON.stringify({type:'serve'}));ws.send(JSON.stringify({type:'move',x:b.x,y:b.y+sg*b.z*.38}));}
 else if(b.phase==='flight'&&b.last!==c.side&&b.bounces===1)ws.send(JSON.stringify({type:'move',x:b.x,y:b.y+sg*b.z*.38}));
 else if(b.phase==='flight'&&b.last!==c.side)ws.send(JSON.stringify({type:'move',x:58,y:sg===1?-105:105}));
 }} });await new Promise((res,rej)=>{ws.on('open',res);ws.on('error',rej)});return c;}
async function until(fn,msg){for(let n=0;n<600;n++){if(fn())return;await wait(10);}throw Error(msg);}
(async()=>{
 proc=spawn(process.execPath,['server.js'],{cwd:__dirname,env:{...process.env,PORT:String(port)},stdio:['ignore','pipe','pipe']});proc.stderr.on('data',d=>console.error(String(d)));let output='';proc.stdout.on('data',d=>(output+=d,console.log(String(d))));await until(()=>output.includes('listening'),'server start');
 for(const url of ['/play','/three.module.js','/three.core.js']){const r=await new Promise((res,rej)=>require('node:http').get(`http://127.0.0.1:${port}${url}`,response=>{let body='';response.on('data',d=>body+=d);response.on('end',()=>res({status:response.statusCode,text:body}));}).on('error',rej));assert.equal(r.status,200);const text=r.text;assert(text.length>1000);if(url==='/play'){assert(text.includes("location.protocol==='https:'"));assert(text.includes("import * as THREE from '/three.module.js'"));assert(!text.includes("const WS_URL = 'wss://YOUR-SERVER-DOMAIN.example'"));}}
 const a=await client(),b=await client(),c=await client();a.ws.send(JSON.stringify({type:'create',name:'A',token:'a'}));await until(()=>a.latest,'created');b.ws.send(JSON.stringify({type:'join',name:'B',token:'b',id:a.latest.id}));await until(()=>a.latest.status==='ready'&&b.latest?.status==='ready','ready');a.auto=b.auto=true;a.ws.send(JSON.stringify({type:'ready'}));b.ws.send(JSON.stringify({type:'ready'}));await until(()=>a.lastShot>=6,'six real network hits');assert.equal(a.latest.score[0]+a.latest.score[1],0,'projected contacts keep rally alive');
 a.ws.send(JSON.stringify({type:'ping',sent:123}));await until(()=>a.events.some(e=>e.type==='pong'&&e.sent===123),'ping echo');assert(c.events.some(e=>e.type==='lobby'&&e.tables.some(t=>t.status==='playing')),'third visitor sees active table');
 a.auto=b.auto=false;b.ws.send(JSON.stringify({type:'move',x:58,y:112}));a.ws.send(JSON.stringify({type:'move',x:58,y:-112}));await until(()=>a.latest.score[0]+a.latest.score[1]>0,'miss scores once');const total=a.latest.score[0]+a.latest.score[1];await wait(80);assert.equal(a.latest.score[0]+a.latest.score[1],total,'no duplicate point');await until(()=>c.events.some(e=>e.type==='lobby'&&e.tables.some(t=>t.score[0]+t.score[1]===total)),'live lobby score');
 for(const q of [a,b,c])q.ws.close();console.log('PASS: HTTP LAN assets, three clients, ready handshake, 6 returned shots, ping echo, live lobby score, round lock');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>proc?.kill());
